apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<Accound_ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D61KBKI47ZIM
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::<Accound_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-09T19:22:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-12-09T19:22:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1371"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: aadd5fb3-7875-4ada-940c-66ff8f780ef0
